# Generated by Django 4.2.4 on 2023-09-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_buyerinfo_companyinfo_product_producttype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
